export const BASE_URL = 'https://dummyur';
export const CMS_BASE_URL = 'https://cmsapi/';

export const STATE_STATUS = {
  FETCHING: 'FETCHING',
  FETCHED: 'FETCHED',
  FAILED_FETCH: 'FAILED_FETCH',
  UNFETCHED: 'UNFETCHED',
  SERVER_ERROR: 'SERVER_ERROR',
  UPDATED: 'UPDATED',
  UPDATING: 'UPDATING',
  NOT_UPDATED: 'NOT_UPDATED',
  FAILED_UPDATE: 'FAILED_UPDATE',
};
